name: 'Maven Central Release Action'
description: 'Publish Maven artifact to Maven Central'
inputs:
  profile:  # id of input
    description: 'Profile'
    required: true
  sona:  # id of input
    description: 'creds'
    required: true
  repoid:  # id of input
    description: 'repoid'
    required: true
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/release.sh ${{ inputs.sona }} ${{ inputs.profile }} ${{ inputs.repo-id }}
      shell: bash