name: 'Maven Central Action'
description: 'Publish Maven artifact to Maven Central'
inputs:
  version:  # id of input
    description: 'version of artifacts'
    required: true
    default: 'version'
  gpg_key:  # id of input
    description: 'gpg key'
    required: true
outputs:
  repo-id:
    description: "Staging repo ID"
    value: ${{ steps.staging.outputs.repo-id }}

runs:
  using: "composite"
  steps:
    - run: sudo apt-get install -y python3 && pip3 install --user bs4 requests
      shell: bash
    - name: Configure GPG Key
      run: |
        mkdir -p ~/.gnupg/
        printf ${{ inputs.gpg_key }} | base64 --decode > ~/.gnupg/private.key
        gpg --import ~/.gnupg/private.key
      shell: bash
    - run: ${{ github.action_path }}/pull.sh ${{ inputs.version }}
      shell: bash
    - run: ${{ github.action_path }}/sign.sh ${{ inputs.sona }} ${{ inputs.profile }} 
      shell: bash
    - id: staging
      run: echo "::set-output name=repo-id::$(echo macy-100)"
      shell: bash
    - run: ${{ github.action_path }}/release.sh ${{ steps.staging.outputs.repo-id }}
      shell: bash