name: 'Maven Central Action'
description: 'Publish Maven artifact to Maven Central'
inputs:
  version:  # id of input
    description: 'version of artifacts'
    required: true
    default: 'version'
  gpg_key:  # id of input
    description: 'gpg key'
    required: true
  profile:  # id of input
    description: 'Profile'
    required: true
  sona:  # id of input
    description: 'creds'
    required: true
  gtoken:  # id of input
    description: 'github token'
    required: true
outputs:
  repo-id:
    description: "Staging repo ID"
    value: ${{ steps.staging.outputs.repo-id }}

runs:
  using: "composite"
  steps:
    - run: sudo apt-get install -y jq
      shell: bash
    - name: Configure GPG Key
      run: |
        mkdir -p ~/.gnupg/
        printf ${{ inputs.gpg_key }} | base64 --decode > ~/.gnupg/private.key
        gpg --import ~/.gnupg/private.key
      shell: bash
    - run: ${{ github.action_path }}/pull.sh ${{ inputs.version }} ${{inputs.gtoken}}
      shell: bash
    - run: ${{ github.action_path }}/sign.sh ${{ inputs.version }}
      shell: bash
    - id: staging
      run: ${{ github.action_path }}/stage.sh ${{ inputs.version }} ${{ inputs.sona }} ${{ inputs.profile }} && echo "::set-output name=repo-id::$(echo $(awk -F '[<>]' '/stagedRepositoryId/{print $3}' ./finish.xml))" 
      shell: bash
    - run: ${{ github.action_path }}/release.sh ${{ steps.staging.outputs.repo-id }}
      shell: bash